# Generated by Django 4.0.3 on 2022-03-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_banner_image_homepage_certificate1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='certificate1_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='certificate2_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
