# Generated by Django 4.0.3 on 2022-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_certificate1_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='working_time',
            field=models.CharField(default=-6, max_length=50),
            preserve_default=False,
        ),
    ]
