# Generated by Django 4.0.3 on 2022-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_working_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='thankyou_page_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
